version: '3.8'

services:
  mail_parser:
    image: ppawlowski186/mailparser:1.1
    container_name: mail_parser
    environment:
      IMAP_PORT: 993
      POLL_INTERVAL: 30
    env_file:
      - .env
    restart: always